[package]
name = "SSFTP"
version = "0.1.0"
authors = ["russon@awty.org <russon@awty.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.29"
